module.exports = {
  browserEvents: {
    REDUX_ACTION_DISPATCHED: '@BROWSER/REDUX_ACTION_DISPATCHED',
    REDUX_STORE_CREATED: '@BROWSER/REDUX_STORE_CREATED',
    SET_SOURCE_CODE: '@BROWSER/SOURCE_CHANGED_IN_BROWSER',
  },
  mainEvents: {
    DISPATCH_ACTION: '@MAIN/DISPATCH_ACTION',
    SET_TRANSFORM_PARSER: '@MAIN/SET_TRANSFORM_PARSER',
    SET_SOURCE_CODE: '@MAIN/SOURCE_CHANGED_ON_DISK',
    SET_TRANSFORM_CODE: '@MAIN/TRANSFORM_CHANGED_ON_DISK',
  },
};
